Console.Write("Ведите число a:");
int a=Convert.ToInt32(Console.ReadLine());
Console.Write("Ведите число b:");
int b=Convert.ToInt32(Console.ReadLine());
Console.Write("Ведите число c:");
int c=Convert.ToInt32(Console.ReadLine());
int max=a;
if (b>max) max=b;
if (c>max) max=c;
Console.WriteLine(max);